### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [shege68/grid-template#1]
Внешний вид не соответствует поставленной задаче.
Сравните результат с макетом или мастер шаблоном.

![image](https://user-images.githubusercontent.com/8464662/234919650-1a34b40d-2cfc-4a12-b979-63e4de39d86a.png)

**Comment by shege68** [comment]
помилку виправив.
сторінка: https://shege68.github.io/grid-template/
репозиторій: https://github.com/shege68/grid-template

**Comment by Alecto** [comment]
Теперь хорошо, больше ошибок и замечаний нет.
Работа принята.

напишите ФИО и группу, чтобы можно было поставить оценку в журнал

сб, 6 трав. 2023 р. о 18:06 shege68 ***@***.***> пише:

**Comment by shege68** [comment]
Дуже дякую.
група: SkillUp FrontEnd. Шевченко Геннадій, пн/ср 19-30
